apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: terje-spk

resources:
  - service.yaml
  - http-route.yaml
  - deployment.yaml

configMapGenerator:
  - name: whatami-config
    namespace: terje-spk
    literals:
      - WHOAMI_PORT_NUMBER=8080
